### ISSUE TITLE
First route change will reset the state

### ISSUE THREAD

**Issue by bkniffler** [coodoo/react-redux-isomorphic-example#8] opened 2015-07-28 10:18 UTC
Hey, 
I noticed that the first route change resets the state, subsequent changes will work as expected.

**Comment by bkniffler** [comment] 2015-07-28 10:39
edit: it seems like only the item amounts are resetted, not the shopping cart.

**Comment by coodoo** [comment] 2015-07-31 14:40
It's caused by `api/shop` always returning the same set of mockdata, it's fixed now, thanks for reporting.

**Closed as completed by coodoo** 2015-07-31 14:40 UTC
